# Generated by Django 6.1 on 2026-08-12 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=128)),
                ('institution_address', models.CharField(blank=True, max_length=64)),
                ('specialist', models.CharField(max_length=64)),
                ('specialist_full_name', models.CharField(max_length=64)),
                ('office', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_and_time', models.DateTimeField()),
                ('patient', models.CharField(max_length=64)),
            ],
        ),
    ]
