[project]
name = "tb-elmosoft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "packletka", email = "pavel.azyava@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django==6.1",
    "djangorestframework==3.18.0",
    "gunicorn==26.0.0",
    "psycopg2-binary==2.9.12",
    "python-dotenv==1.2.2",
    "redis==8.0.0",
    "uv==0.12.3",
    "whitenoise==6.12.0",
    "pre_commit==4.6.2",
    "ruff==0.16.3",
]

# Commented out in order to avoid an error like
# Failed to build `tb-elmosoft @ file:///home/packletka/TB_Elmosoft`
#  ╰─▶ Expected a Python module at: src/tb_elmosoft/__init__.py

#[build-system]
#requires = ["uv_build>=0.12.3,<0.13.0"]
#build-backend = "uv_build"
#module-name = "backend"


[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
extend-select = ["E501"]

[tool.ruff.lint.per-file-ignores]
"*/migrations/*" = ["RUF012", "E501"]
