# Generated by Django 6.1 on 2026-08-24 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talons",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.doctor")),
            ],
            options={
                "unique_together": {("doctor", "date", "time")},
            },
        ),
    ]
