# Generated by Django 6.1 on 2026-08-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("users", "0002_customuser_doctor_representative_delete_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talons",
            name="doctor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.doctor"),
        ),
        migrations.AlterUniqueTogether(
            name="talons",
            unique_together={("doctor", "date", "time")},
        ),
    ]
