# Generated by Django 6.1 on 2026-08-21 15:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthOrganisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("address", models.TextField()),
                ("general_info", models.TextField(blank=True, default="")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="", max_length=128, region="BY"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("site", models.CharField(blank=True, max_length=50)),
                ("schedule", models.TextField()),
            ],
        ),
    ]
