# Generated by Django 6.1 on 2026-08-27 14:17

from django.db import migrations, models

import health_organisations.utils


class Migration(migrations.Migration):
    dependencies = [
        ("health_organisations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthorganisation",
            name="schedule",
            field=models.JSONField(validators=[health_organisations.utils.validate_schedule_structure]),
        ),
    ]
