# Generated by Django 6.1 on 2026-08-20 11:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_name", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("patronymic", models.CharField(blank=True, default="", max_length=20)),
                ("sex", models.CharField(choices=[("M", "Male"), ("F", "Female")])),
                ("birthday_date", models.DateField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, default="", max_length=128, region="BY"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("territorial_polyclinic", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="HealthOrganisationRepresentative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_name", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("patronymic", models.CharField(blank=True, default="", max_length=20)),
                ("position", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, height_field=640, upload_to="", width_field=360),
                ),
                ("work_schedule", models.TextField()),
                ("is_on_vacation", models.BooleanField(choices=[("Y", "Yes"), ("N", "No")])),
            ],
        ),
    ]
