# Generated by Django 6.1 on 2026-08-21 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_doctor_representative_delete_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="health_organisation",
        ),
        migrations.RemoveField(
            model_name="representative",
            name="health_organisation",
        ),
    ]
