# Generated by Django 6.1 on 2026-09-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_organisations", "0002_alter_healthorganisation_schedule"),
        ("users", "0002_customuser_groups_customuser_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="health_organisations.healthorganisation",
            ),
        ),
    ]
