# Generated by Django 6.1 on 2026-08-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_organisations", "0001_initial"),
        ("users", "0003_remove_doctor_health_organisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="health_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="health_organisations.healthorganisation",
            ),
        ),
        migrations.AddField(
            model_name="representative",
            name="health_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="health_organisations.healthorganisation",
            ),
        ),
    ]
